### ISSUE TITLE
skipping resolution of commit since it originates from another repository

### ISSUE THREAD

**Issue by slynTEN** [jenkinsci/bitbucket-push-and-pull-request-plugin#198]
We are trying to to trigger jenkins job build a specified commit through bitbucket webhook.
But we are facing the issue "skipping resolution of commit 413cebbede802f99119ca5b8ee4e8afcc0cda334, since it originates from another repository" than the job build the master branch we don't want.
The bitbucket send clone url like :
"clone": [{
"href": "ssh://git@mydomain:7999/myproject/myrepo.git",
"name": "ssh"
}, {
"href": "https://mydomain/scm/myproject/myrepo.git",
"name": "http"
}],
And the BPPRP will regard the first url as the goal url. So it will be different with the bitbucket repo we configure in jenkins job. That caused that jenkins regard the commit from other repo.
Actually the BPPRP should regard all clone url from bitbucket.
Can you please help to fix this issue?
Thanks

**Comment by kafteji** [comment]
I have faced the same issue. It happens when you force push an amended commit 
I managed to have a reproducible environment. hopefully it helps
Steps to reproduce:

1. Push a PR and check if the build is triggered in jenkins via bitbucket-push-and-pull-request-plugin. (bitbucket branch specifiers are set to ** for BPPRP and */* for git plugin )

2. Check the sha of the commit in bitbucket PR commit summary.

3. Make a code change, commit amend and force push the change (you will see that the commit sha has changed in the PR overview).

4. Check that jenkins has been triggered and you will see that the build fail with error (stderr: fatal: reference is not a tree: a5b47104e757b867e58f0e564b439e8d2f770ed6) or whatever commit sha you have

Log:
```bash
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
The recommended git tool is: /usr/bin/git

using credential bb202df4-55f2-4c35-8c49-bd821a020498
Cloning the remote Git repository

Cloning repository git@bitbucket.org:space/my-repo.git
 > /usr/bin/git init /home/jenkins/agent/workspace/my-test-job # timeout=10
Fetching upstream changes from git@bitbucket.org:space/my-repo.git
 > /usr/bin/git --version # timeout=10
 > git --version # 'git version 2.20.1'
using GIT_SSH to set credentials foo Bitbucket
 > /usr/bin/git fetch --tags --force --progress -- git@bitbucket.org:space/my-repo.git +refs/heads/*:refs/remotes/origin/* # timeout=10

 > /usr/bin/git config remote.origin.url git@bitbucket.org:space/my-repo.git # timeout=10
 > /usr/bin/git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > /usr/bin/git config remote.origin.url git@bitbucket.org:space/my-repo.git # timeout=10
Fetching upstream changes from git@bitbucket.org:space/my-repo.git
using GIT_SSH to set credentials foo Bitbucket
 > /usr/bin/git fetch --tags --force --progress -- git@bitbucket.org:space/my-repo.git +refs/heads/*:refs/remotes/origin/* # timeout=10
skipping resolution of commit 4d5740fbab24, since it originates from another repository

Checking out Revision a5b47104e757b867e58f0e564b439e8d2f770ed6 (origin/feature/DS-2815-event-service)
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
Seen branch in repository origin/DS-3059-dockerfile-components
Seen branch in repository origin/feature/DS-2815-event-service
Seen branch in repository origin/main
Seen 3 remote branches
 > /usr/bin/git show-ref --tags -d # timeout=10
 > /usr/bin/git config core.sparsecheckout # timeout=10
 > /usr/bin/git checkout -f a5b47104e757b867e58f0e564b439e8d2f770ed6 # timeout=10
[Pipeline] }
[Pipeline] // podTemplate
[Pipeline] End of Pipeline
hudson.plugins.git.GitException: Command "/usr/bin/git checkout -f a5b47104e757b867e58f0e564b439e8d2f770ed6" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: a5b47104e757b867e58f0e564b439e8d2f770ed6

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2681)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$1100(CliGitAPIImpl.java:86)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2999)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from server
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1797)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.base/java.lang.reflect.Method.invoke(Unknown Source)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
		at com.sun.proxy.$Proxy96.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1352)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)
		at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.base/java.lang.Thread.run(Unknown Source)
Caused: hudson.plugins.git.GitException: Could not checkout a5b47104e757b867e58f0e564b439e8d2f770ed6
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:3023)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:160)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:117)
	at java.base/java.lang.Thread.run(Thread.java:834)
Finished: FAILURE

```

**Comment by kafteji** [comment]
Issue is reported to Jenkins developers team as well https://issues.jenkins.io/browse/JENKINS-67073

**Comment by slynTEN** [comment]
We have locate the code.
We think is not too difficult to fix.
Please help take some time for that, thanks.
https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/blob/2b7f17194ac4f8e8febe14c73465a0f13e13cf1e/src/main/java/io/jenkins/plugins/bitbucketpushandpullrequest/BitBucketPPRTrigger.java#L205
https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/blob/2b7f17194ac4f8e8febe14c73465a0f13e13cf1e/src/main/java/io/jenkins/plugins/bitbucketpushandpullrequest/action/BitBucketPPRPullRequestServerAction.java#L54

**Comment by zeeshanali2021** [comment]
![image](https://user-images.githubusercontent.com/78139610/144826798-87d24151-ccaf-4fc8-8232-4ee9dee60682.png)
Hi Everyone, facing the same issue on PR create  and update action. BPPRP is triggering build on target branch instead of PR branch (source branch).

**Comment by cyberguard** [comment]
This seem to be the same issue as me : https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/issues/188 

I did write up some code to fix it and it work (for us, I compiled the jar and overwrote the one in our jenkins dir), but still did not get the time to vet it and make sure it was the most optimal approach.

The approach I took was to simply overwrite the git repo that we get from the webhook so that it match the repos checkout by the scm plugin.

**Comment by cdelmonte-zg** [comment]
Hi @zeeshanali2021 

could the solution proposed by @cyberguard  work also for you?

**Comment by kafteji** [comment]
I managed to fix the issue and it's now working as expected:
1. in BBPPR plugin config just allow every branch with "**"
2. in the git plugin use origin/${BITBUCKET_SOURCE_BRANCH} as branch regex. The BITBUCKET_SOURCE_BRANCH will be populated automatically for you by the BBPPR plugin.
I hope it helps

**Comment by Yonnatan** [comment]
@kafteji , 
Bitbucket sends a webhook for every Push/PR .
Your solution prevents from filtering specific branches on the Job and results for every Webhook to trigger a Job , 
Its impossible to implement in cases where you have Jobs where you wish to deploy a code from specific branch only, and end up deploying code after every push .

**Comment by binakot** [comment]
Hello there.
I faced to the same problem with Jenkins using self-hosted GitLab.
If you see something like `skipping resolution of commit since it originates from another repository` in logs of PR/MR builds just update few parameters in Jenkins job:
* `Pipeline/SCM/Repositories/Refspec` to `+refs/merge-requests/*/head:refs/remotes/origin/merge-requests/*`
* `Pipeline/SCM/Branches to build/Branch Specifier` to `origin/merge-requests/${gitlabMergeRequestIid}` 
And now it will wokrs like a charm :)

![image](https://github.com/jenkinsci/bitbucket-push-and-pull-request-plugin/assets/1783893/349f22be-3f8f-44b2-9a19-21a2f4d42d2d)
