### ISSUE TITLE
Version 1.6.2 throws exception after receiving PR payload

### ISSUE THREAD

**Issue by ozgur** [jenkinsci/bitbucket-push-and-pull-request-plugin#30]
Hello @cdelmonte-zg ;
We are getting a null pointer exception from the plugin for the any kind of event (push/merged/created etc.).

- [x] You're not able to fix the problem yourself and send us a pull request instead of an issue.
- [x] There is no existing issue regarding the same topic

* Plugin Version: 1.6.2
* Jenkins Version: 2.150.2
* Jenkins Job Type: Freestyle
* Triggered via: Bitbucket Cloud

# Expected Behavior
Payloads coming as a result of a webhook must be processed correctly.

# Actual Behavior
We are getting a null pointer exception from the plugin for the any kind of event (push/merged/created etc.).

## Jenkins Job configuration

![Screen Shot 2019-05-13 at 16 12 44](https://user-images.githubusercontent.com/43006/57624186-1b016380-759a-11e9-9b15-3e1ec0c5cd16.png)

![Screen Shot 2019-05-13 at 16 12 51](https://user-images.githubusercontent.com/43006/57624192-1d63bd80-759a-11e9-8394-24c37f7ff9a4.png)

# Context
How has this issue affected you? What are you trying to accomplish?
Providing context helps us come up with a solution that is most useful in the real world.

## Bitbucket payload
```
{
  "push": {
    "changes": [
      {
        "forced": false,
        "old": {
          "name": "development",
          "links": {
            "commits": {
              "href": "..."
            },
            "self": {
              "href": "..."
            },
            "html": {
              "href": "https://bitbucket.org/..."
            }
          },
          "default_merge_strategy": "merge_commit",
          "merge_strategies": [
            "merge_commit",
            "squash",
            "fast_forward"
          ],
          "type": "branch",
          "target": {
            "rendered": {},
            "hash": "69d4aa9af17aa3dec1b845ef6b8f0a8fd1cd50f8",
            "links": {
              "self": {
                "href": "https://api.bitbucket.org/2.0/repositories/.../69d4aa9af17aa3dec1b845ef6b8f0a8fd1cd50f8"
              },
              "html": {
                "href": "https://bitbucket.org/..."
              }
            },
            "author": {
              "raw": "Özgür Vatansever <...>",
              "type": "author",
              "user": {
                "username": "...",
                "display_name": "Özgür Vatansever",
                "uuid": "...",
                "links": {
                  "self": {
                    "href": "https://api.bitbucket.org/2.0/users/..."
                  },
                  "html": {
                    "href": "https://bitbucket.org/.../"
                  },
                  "avatar": {
                    "href": "..."
                  }
                },
                "nickname": "Özgür Vatansever",
                "type": "user",
                "account_id": "5b5586c6f220fc2d9cb5c74a"
              }
            },
            "summary": {
              "raw": "Merged in feature/commit-message-prepend-branch (pull request #106)\n\nHook for checking and prepending branch name into commit message\n\nApproved-by: Vidal HARA <...>\nApproved-by: Umut Tuzcu <...>\n",
              "markup": "markdown",
              "html": "<p>Merged in feature/commit-message-prepend-branch (pull request #106)</p>\n<p>Hook for checking and prepending branch name into commit message</p>\n<p>Approved-by: Vidal HARA ...",
              "type": "rendered"
            },
            "parents": [
              {
                "hash": "972918fc8f2fdea4780c99ce5885d3055d61afbc",
                "type": "commit",
                "links": {
                  "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/..."
                  },
                  "html": {
                    "href": "https://bitbucket.org/.../..."
                  }
                }
              },
              {
                "hash": "86ecb44d42a10090eda99db4ecb54e59bf8bf363",
                "type": "commit",
                "links": {
                  "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/..."
                  },
                  "html": {
                    "href": "https://bitbucket.org/.../..."
                  }
                }
              }
            ],
            "date": "2019-05-13T09:25:46+00:00",
            "message": "Merged in feature/commit-message-prepend-branch ...",
            "type": "commit",
            "properties": {}
          }
        },
        "links": {
          "commits": {
            "href": "https://api.bitbucket.org/2.0/repositories/..."
          },
          "html": {
            "href": "https://bitbucket.org/.../..."
          },
          "diff": {
            "href": "https://api.bitbucket.org/2.0/repositories/..."
          }
        },
        "created": false,
        "commits": [
          {
            "rendered": {},
            "hash": "09bf41c8afac69aa7aea9e5d87ea7d770cd789ad",
            "links": {
              "self": {
                "href": "https://api.bitbucket.org/2.0/repositories/..."
              },
              "comments": {
                "href": "https://api.bitbucket.org/2.0/repositories/..."
              },
              "patch": {
                "href": "https://api.bitbucket.org/2.0/repositories/..."
              },
              "html": {
                "href": "https://bitbucket.org/..."
              },
              "diff": {
                "href": "https://api.bitbucket.org/2.0/repositories/..."
              },
              "approve": {
                "href": "https://api.bitbucket.org/2.0/repositories/..."
              },
              "statuses": {
                "href": "https://api.bitbucket.org/2.0/repositories/..."
              }
            },
            "author": {
              "raw": "Ozgur Vatansever ...",
              "type": "author",
              "user": {
                "username": "...",
                "display_name": "Özgür Vatansever",
                "uuid": "...",
                "links": {
                  "self": {
                    "href": "https://api.bitbucket.org/2.0/users/..."
                  },
                  "html": {
                    "href": "https://bitbucket.org/.../"
                  },
                  "avatar": {
                    "href": "..."
                  }
                },
                "nickname": "Özgür Vatansever",
                "type": "user",
                "account_id": "..."
              }
            },
            "summary": {
              "raw": "[development] - updated agent label\n",
              "markup": "markdown",
              "html": "<p>[development] - updated agent label</p>",
              "type": "rendered"
            },
            "parents": [
              {
                "hash": "69d4aa9af17aa3dec1b845ef6b8f0a8fd1cd50f8",
                "type": "commit",
                "links": {
                  "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/..."
                  },
                  "html": {
                    "href": "https://bitbucket.org/..."
                  }
                }
              }
            ],
            "date": "2019-05-13T10:49:01+00:00",
            "message": "[development] - updated agent label\n",
            "type": "commit",
            "properties": {}
          }
        ],
        "truncated": false,
        "closed": false,
        "new": {
          "name": "development",
          "links": {
            "commits": {
              "href": "https://api.bitbucket.org/2.0/repositories/.../commits/development"
            },
            "self": {
              "href": "https://api.bitbucket.org/2.0/repositories/..."
            },
            "html": {
              "href": "https://bitbucket.org/..."
            }
          },
          "default_merge_strategy": "merge_commit",
          "merge_strategies": [
            "merge_commit",
            "squash",
            "fast_forward"
          ],
          "type": "branch",
          "target": {
            "rendered": {},
            "hash": "09bf41c8afac69aa7aea9e5d87ea7d770cd789ad",
            "links": {
              "self": {
                "href": "https://api.bitbucket.org/2.0/repositories..."
              },
              "html": {
                "href": "https://bitbucket.org/..."
              }
            },
            "author": {
              "raw": "Ozgur Vatansever ...",
              "type": "author",
              "user": {
                "username": "...",
                "display_name": "Özgür Vatansever",
                "uuid": "...",
                "links": {
                  "self": {
                    "href": "https://api.bitbucket.org/2.0/users/..."
                  },
                  "html": {
                    "href": "https://bitbucket.org/.../"
                  },
                  "avatar": {
                    "href": "..."
                  }
                },
                "nickname": "Özgür Vatansever",
                "type": "user",
                "account_id": "..."
              }
            },
            "summary": {
              "raw": "[development] - updated agent label\n",
              "markup": "markdown",
              "html": "<p>[development] - updated agent label</p>",
              "type": "rendered"
            },
            "parents": [
              {
                "hash": "69d4aa9af17aa3dec1b845ef6b8f0a8fd1cd50f8",
                "type": "commit",
                "links": {
                  "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/..."
                  },
                  "html": {
                    "href": "https://bitbucket.org/..."
                  }
                }
              }
            ],
            "date": "2019-05-13T10:49:01+00:00",
            "message": "[development] - updated agent label\n",
            "type": "commit",
            "properties": {}
          }
        }
      }
    ]
  },
  "actor": {
    "username": "...",
    "display_name": "Özgür Vatansever",
    "uuid": "...",
    "links": {
      "self": {
        "href": "https://api.bitbucket.org/2.0/users/..."
      },
      "html": {
        "href": "https://bitbucket.org/.../"
      },
      "avatar": {
        "href": "..."
      }
    },
    "nickname": "Özgür Vatansever",
    "type": "user",
    "account_id": "..."
  },
  "repository": {
    "scm": "git",
    "website": "https://bitbucket.org/...",
    "name": "...",
    "links": {
      "self": {
        "href": "https://api.bitbucket.org/2.0/repositories/..."
      },
      "html": {
        "href": "https://bitbucket.org/..."
      },
      "avatar": {
        "href": "..."
      }
    },
    "project": {
      "key": "...",
      "type": "project",
      "uuid": "...",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/teams/.../projects/..."
        },
        "html": {
          "href": "https://bitbucket.org/account/user/.../projects/..."
        },
        "avatar": {
          "href": "https://bitbucket.org/account/user/.../projects/.../avatar/32"
        }
      },
      "name": "..."
    },
    "full_name": "...",
    "owner": {
      "username": "...",
      "display_name": "...",
      "type": "team",
      "uuid": "...",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/teams/..."
        },
        "html": {
          "href": "https://bitbucket.org/.../"
        },
        "avatar": {
          "href": "https://bitbucket.org/account/.../avatar/"
        }
      }
    },
    "type": "repository",
    "is_private": true,
    "uuid": "..."
  }
}
```
Only if relevant. Mainly scm and plugin parts will be helpful for reproducing the issue

## Jenkins logs

```
May 13, 2019 1:05:55 PM io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
INFO: Sending response.
May 13, 2019 1:05:55 PM io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
INFO: Response sent.
May 13, 2019 1:05:55 PM io.jenkins.plugins.bitbucketpushandpullrequest.environment.BitBucketPPRAdditionalParameterServerRepositoryEnvironmentContributor buildEnvironmentFor
INFO: Injecting env vars because of server push cause.
May 13, 2019 1:05:55 PM io.jenkins.plugins.bitbucketpushandpullrequest.environment.BitBucketPPRAdditionalParameterServerRepositoryEnvironmentContributor buildEnvironmentFor
WARNING: Problem injecting env variables: Cause = null
May 13, 2019 1:05:55 PM io.jenkins.plugins.bitbucketpushandpullrequest.environment.BitBucketPPRAdditionalParameterRepositoryEnvironmentContributor buildEnvironmentFor
INFO: Injecting env vars because of push cause.
May 13, 2019 1:05:55 PM io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRPollingRunnable run
SEVERE: Failed to record SCM polling
java.lang.NullPointerException
	at io.jenkins.plugins.bitbucketpushandpullrequest.action.BitBucketPPRRepositoryAction.getRepositoryUrl(BitBucketPPRRepositoryAction.java:58)
	at io.jenkins.plugins.bitbucketpushandpullrequest.environment.BitBucketPPRAdditionalParameterRepositoryEnvironmentContributor.buildEnvironmentFor(BitBucketPPRAdditionalParameterRepositoryEnvironmentContributor.java:43)
	at hudson.model.Run.getEnvironment(Run.java:2373)
	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:872)
	at hudson.plugins.git.GitSCM.getParamExpandedRepos(GitSCM.java:484)
	at hudson.plugins.git.GitSCM.compareRemoteRevisionWithImpl(GitSCM.java:693)
	at hudson.plugins.git.GitSCM.compareRemoteRevisionWith(GitSCM.java:658)
	at hudson.scm.SCM.compareRemoteRevisionWith(SCM.java:400)
	at hudson.scm.SCM.poll(SCM.java:417)
	at hudson.model.AbstractProject._poll(AbstractProject.java:1390)
	at hudson.model.AbstractProject.poll(AbstractProject.java:1293)
	at io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRPollingRunnable.run(BitBucketPPRPollingRunnable.java:66)
	at hudson.util.SequentialExecutionQueue$QueueEntry.run(SequentialExecutionQueue.java:119)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cdelmonte-zg** [comment]
Hi @ozgur ,  can you install the new beta version of the plugin **bitbucket-push-and-pull-request-1.6.3-beta-1** using the experimental repository of Jenkins? 

You can download experimental plugin releases you need to go to to Plugin Manager, then to the Advanced tab, and configure the update center URL with: 
https://updates.jenkins.io/experimental/update-center.json.
 
For more details: [Using the Experimental Update Center](https://jenkins.io/doc/developer/publishing/releasing-experimental-updates/)

**Comment by ozgur** [comment]
Hi @cdelmonte-zg ,

After I upgraded to `1.6.3-beta-1`, it still got the same exception when I triggered `repo:push` with same payload.

**Comment by cdelmonte-zg** [comment]
HI @ozgur,
can you add the stack trace of the last exception with  1.6.3-beta-1?
Is it working now with the pull requests?

**Comment by cdelmonte-zg** [comment]
Closed due to inactivity

**Comment by OneXeor** [comment]
I have the same issue
