### ISSUE TITLE
Everything broke down on version 3.1.2 (FIX - roll back to 3.1.1)

### ISSUE THREAD

**Issue by x4team** [jenkinsci/bitbucket-push-and-pull-request-plugin#350]
More than 20 jobs were configured in jenkins, now they start with the error "no commit found during checkout"

```
Fetching without tags
Fetching upstream changes from git@bitbucket.org:sk/infr.git
 > git --version # timeout=10
 > git --version # 'git version 2.39.2'
using GIT_SSH to set credentials Bitbucket
Verifying host key using known hosts file, will automatically accept unseen keys
 > git fetch --no-tags --force --progress -- git@bitbucket.org:sk/infr.git +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git rev-parse a50c232f6fea76b00c2ecd6d25202783f127e998^{commit} # timeout=10
ERROR: Checkout failed
hudson.plugins.git.GitException: Command "git rev-parse a50c232f6fea76b00c2ecd6d25202783f127e998^{commit}" returned status code 128:
stdout: a50c232f6fea76b00c2ecd6d25202783f127e998^{commit}

stderr: fatal: ambiguous argument 'a50c232f6fea76b00c2ecd6d25202783f127e998^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2846)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2766)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2761)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:2051)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:2063)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:1115)
	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:419)
	at hudson.plugins.git.RevisionParameterAction.toRevision(RevisionParameterAction.java:98)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1136)
	at hudson.plugins.git.GitSCM._checkout(GitSCM.java:1311)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1277)
Caused: java.io.IOException
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1279)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:136)
	at org.jenkinsci.plugins.workflow.libs.SCMBasedRetriever.lambda$doRetrieve$4(SCMBasedRetriever.java:200)
	at org.jenkinsci.plugins.workflow.libs.SCMBasedRetriever.retrySCMOperation(SCMBasedRetriever.java:222)
	at org.jenkinsci.plugins.workflow.libs.SCMBasedRetriever.doRetrieve(SCMBasedRetriever.java:199)
	at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.retrieve(SCMSourceRetriever.java:79)
	at org.jenkinsci.plugins.workflow.libs.LibraryAdder.retrieve(LibraryAdder.java:298)
	at org.jenkinsci.plugins.workflow.libs.LibraryAdder.add(LibraryAdder.java:157)
	at org.jenkinsci.plugins.workflow.libs.LibraryDecorator$1.call(LibraryDecorator.java:125)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1087)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:624)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:602)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:323)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:293)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox$Scope.parse(GroovySandbox.java:163)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:190)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:175)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:652)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:598)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:335)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
ERROR: Maximum checkout retry attempts reached, aborting
ERROR: Checkout failed
hudson.plugins.git.GitException: Command "git rev-parse a50c232f6fea76b00c2ecd6d25202783f127e998^{commit}" returned status code 128:
stdout: a50c232f6fea76b00c2ecd6d25202783f127e998^{commit}

stderr: fatal: ambiguous argument 'a50c232f6fea76b00c2ecd6d25202783f127e998^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2846)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2766)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2761)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:2051)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:2063)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:1115)
	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:419)
	at hudson.plugins.git.RevisionParameterAction.toRevision(RevisionParameterAction.java:98)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1136)
	at hudson.plugins.git.GitSCM._checkout(GitSCM.java:1311)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1277)
Caused: java.io.IOException
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1279)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:136)
	at org.jenkinsci.plugins.workflow.libs.SCMBasedRetriever.lambda$doRetrieve$4(SCMBasedRetriever.java:200)
	at org.jenkinsci.plugins.workflow.libs.SCMBasedRetriever.retrySCMOperation(SCMBasedRetriever.java:222)
	at org.jenkinsci.plugins.workflow.libs.SCMBasedRetriever.doRetrieve(SCMBasedRetriever.java:199)
	at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.retrieve(SCMSourceRetriever.java:79)
	at org.jenkinsci.plugins.workflow.libs.LibraryAdder.retrieve(LibraryAdder.java:298)
	at org.jenkinsci.plugins.workflow.libs.LibraryAdder.add(LibraryAdder.java:157)
	at org.jenkinsci.plugins.workflow.libs.LibraryDecorator$1.call(LibraryDecorator.java:125)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1087)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:624)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:602)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:323)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:293)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox$Scope.parse(GroovySandbox.java:163)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:190)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:175)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:652)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:598)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:335)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
ERROR: Maximum checkout retry attempts reached, aborting
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: Loading libraries failed

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:309)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1107)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:624)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:602)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:323)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:293)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox$Scope.parse(GroovySandbox.java:163)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:190)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:175)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:652)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:598)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:335)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
```

**Temporary fix - roll back to version 3.1.1**

**What is the problem?** Jenkins is trying to pull the commit from the repository where the "shared library" for Jenkins is located (bitbucket.org:sk/infr.git), and not from the repository of the service (bitbucket.org/sk/server-pay.git)

**That is, there was a conflict between the service's build repository and the shared library repository for jenkins**

Additional settings:

![Image](https://github.com/user-attachments/assets/52df4158-2102-4832-ac62-f78377b525d2)
![Image](https://github.com/user-attachments/assets/da3cd37f-01c2-45a4-90c1-be3945a27db0)
![Image](https://github.com/user-attachments/assets/901c5104-30e1-4482-950f-f302fce2d177)

Pipeline:

```
@Library('shared-library') _

node {
     stage('Build')  { build(repo: "serverpay-service", env: "java", version: "17") }
     stage('Upload') { upload(serviceName: env.repo, docker: true) }
}

```

**Comment by cdelmonte-zg** [comment]
@x4team can you please verify if with v3.1.3 is working again correctly? Thank you!

**Comment by x4team** [comment]
> [@x4team](https://github.com/x4team) can you please verify if with v3.1.3 is it working again correctly? Thank you!

Hi Christian, thanks for the new release! 
I see the release on github, but only version 3.1.2 is listed in jenkins plugins, when will version 3.1.3 be available in plugins? The current security policy does not allow me to update in any other way. Thanks

**Comment by x4team** [comment]
> [@x4team](https://github.com/x4team), may you update the plugin list in the plugin management UI? ![Image](https://github.com/user-attachments/assets/61b795a7-dbe4-431a-9803-bbd96a2c513d)

Thanks for the help, it really helped to update the list of plugins (I didn't know before that it could be done manually 😁 )

I tested version 3.1.3, everything is fine! Thanks for this fix 🤝

**Comment by cdelmonte-zg** [comment]
@x4team happy to help :)
