### ISSUE TITLE
Bitbucket Push and Pull Request Plugin does not work

### ISSUE THREAD

**Issue by heathergithub** [jenkinsci/bitbucket-push-and-pull-request-plugin#99]
Jenkins ver. 2.229
Bitbucket Push and Pull Request Plugin 2.3.1

Jenkins reponses webhook, but no build is triggered.

The Jenkins log
![log](https://user-images.githubusercontent.com/16832219/78225177-5f705780-74fc-11ea-9f8f-af7e7a90dabb.PNG)

The webhook
![bbkt-config](https://user-images.githubusercontent.com/16832219/78225171-5d0dfd80-74fc-11ea-8f81-4126673255a2.PNG)

The Jenkins configuration
![jk-config](https://user-images.githubusercontent.com/16832219/78225174-5e3f2a80-74fc-11ea-9afa-6ecabb5ec281.PNG)

**Comment by cdelmonte-zg** [comment]
@heathergithub Are you using Bitbucket Server? Which version?

**Comment by heathergithub** [comment]
Hi @cdelmonte-zg , thanks for the notification of the new version.
Below is the version number I am using:
Atlassian Bitbucket v7.0.1
Jenkins ver. 2.219
Bitbucket Push and Pull Request Plugin 2.3.2

However, this plugin still doesn't work for me.
Just as the picture I attached the last time, I can see system log like this:

```
Apr 13, 2020 9:33:51 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
Received x-event-key pr:opened from Bitbucket
Apr 13, 2020 9:33:51 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
Sending response.
Apr 13, 2020 9:33:51 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
Response sent.
```
But nothing is trigged.
And the message in the "BitBucket Push and Pull Request Hook Log" is:
```
Last BitBucket Push
Polling has not run yet.
```

**Comment by cdelmonte-zg** [comment]
can you find out more logs? Do you have configured your logging system as shown in this screen-shoot?
 
![Screenshot_2020-04-15 Jenkins](https://user-images.githubusercontent.com/23214236/79357110-dd425300-7f3f-11ea-9670-f9c48bc2a819.png)

**Comment by heathergithub** [comment]
Hi @cdelmonte-zg , I am using pipeline.
The bitbucket log is shown as below:
```
Apr 16, 2020 2:08:35 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver

Received commit hook notification : {"eventKey":"pr:opened","date":"2020-04-16T10:11:45+0800","actor":......

Apr 16, 2020 2:08:35 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex

Received x-event-key pr:opened from Bitbucket

Apr 16, 2020 2:08:35 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver

the payload is: {"actor":{"name":......

Apr 16, 2020 2:08:35 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.processor.BitBucketPPRPullRequestServerPayloadProcessor

Processing BitBucketPPREvent [event=pr, action=opened]

Apr 16, 2020 2:08:35 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver

the selected payload processor is: io.jenkins.plugins.bitbucketpushandpullrequest.processor.BitBucketPPRPullRequestServerPayloadProcessor@54d6e89

Apr 16, 2020 2:08:35 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.action.BitBucketPPRPullRequestServerAction

BitBucketPPRPullRequestServerAction was called.

Apr 16, 2020 2:08:35 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe

Considering remote [ssh://git@10.150.9.112:7999/proj1/p1_test1.git, http://10.150.9.112:7990/scm/proj1/p1_test1.git]

Apr 16, 2020 2:08:35 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe

Considering candidate job debug-BitbucketPushAndPullRequest-pipeline

Apr 16, 2020 2:08:35 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe

Considering to poke debug-BitbucketPushAndPullRequest-pipeline

Apr 16, 2020 2:08:35 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex

Sending response.

Apr 16, 2020 2:08:35 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex

Response sent.
```

**Comment by cdelmonte-zg** [comment]
Hi @heathergithub 
may you try with the version 2.3.3 and add the new logs? We added more logging in some relevant code points.

**Comment by heathergithub** [comment]
Hi @cdelmonte-zg ,
Thanks for you response.

Jenkins ver. 2.219
Upgrade the plugin to 2.3.3.
![Screenshot from 2020-04-21 10-47-41](https://user-images.githubusercontent.com/16832219/79819898-9334f380-83bd-11ea-95ac-41ac8a1c0bac.png)

**Bitbucket Webhook configuration**

![Lark20200421-104545](https://user-images.githubusercontent.com/16832219/79819841-713b7100-83bd-11ea-98db-79c3ae658cf1.png)

**Bitbucket Webhook event details**

![Screenshot from 2020-04-21 10-32-08](https://user-images.githubusercontent.com/16832219/79818912-74356200-83bb-11ea-930a-dd4739b92c95.png)

**Build Triggers in Jenkins job:**

![Screenshot from 2020-04-21 10-24-22](https://user-images.githubusercontent.com/16832219/79818737-17d24280-83bb-11ea-96a1-9834bc70df4f.png)

**The log is listed as below:**

```
Apr 21, 2020 2:16:54 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver
Received commit hook notification : {"eventKey":"pr:opened","date":"2020-04-21T10:20:29+0800","actor":{"name":"******","emailAddress":"******","id":2,"displayName":"******","active":true,"slug":"******","type":"NORMAL","links":{"self":[{"href":"http://******/users/******"}]}},"pullRequest":{"id":6,"version":0,"title":"test_branch_20200421101637","state":"OPEN","open":true,"closed":false,"createdDate":1587435629295,"updatedDate":1587435629295,"fromRef":{"id":"refs/heads/test_branch_20200421101637","displayId":"test_branch_20200421101637","latestCommit":"28a828dcac5e08970332decccb0456957ec28fff","repository":{"slug":"p1_test1","id":18,"name":"p1_test1","hierarchyId":"bf7ec189e2f0fb718d94","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"PROJ1","id":24,"name":"project1","public":false,"type":"NORMAL","links":{"self":[{"href":"http://******/projects/PROJ1"}]}},"public":false,"links":{"clone":[{"href":"ssh://git@******/proj1/p1_test1.git","name":"ssh"},{"href":"http://******/scm/proj1/p1_test1.git","name":"http"}],"self":[{"href":"http://******/projects/PROJ1/repos/p1_test1/browse"}]}}},"toRef":{"id":"refs/heads/master","displayId":"master","latestCommit":"5ef23b0bae0f2f5bf42934eb1919334e0c951f7c","repository":{"slug":"p1_test1","id":18,"name":"p1_test1","hierarchyId":"bf7ec189e2f0fb718d94","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"PROJ1","id":24,"name":"project1","public":false,"type":"NORMAL","links":{"self":[{"href":"http://******/projects/PROJ1"}]}},"public":false,"links":{"clone":[{"href":"ssh://git@******/proj1/p1_test1.git","name":"ssh"},{"href":"http://******/scm/proj1/p1_test1.git","name":"http"}],"self":[{"href":"http://******/projects/PROJ1/repos/p1_test1/browse"}]}}},"locked":false,"author":{"user":{"name":"******","emailAddress":"******","id":2,"displayName":"******","active":true,"slug":"******","type":"NORMAL","links":{"self":[{"href":"http://******/users/******"}]}},"role":"AUTHOR","approved":false,"status":"UNAPPROVED"},"reviewers":[],"participants":[],"links":{"self":[{"href":"http://******/projects/PROJ1/repos/p1_test1/pull-requests/6"}]}}}
Apr 21, 2020 2:16:54 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
Received x-event-key pr:opened from Bitbucket
Apr 21, 2020 2:16:54 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver
the payload is: {"actor":{"name":"******","emailAddress":"******","id":"2","displayName":"******","active":true,"slug":"******","type":"NORMAL","links":{"clone":[],"self":[{"href":"http://******/users/******"}]}},"pullRequest":{"id":6,"version":0,"title":"test_branch_20200421101637","state":"OPEN","open":true,"closed":false,"createdDate":1587435629295,"updatedDate":1587435629295,"locked":false,"author":{"active":false},"reviewers":[],"participants":[],"links":{"clone":[],"self":[{"href":"http://******/projects/PROJ1/repos/p1_test1/pull-requests/6"}]},"fromRef":{"id":"refs/heads/test_branch_20200421101637","displayId":"test_branch_20200421101637","latestCommit":"28a828dcac5e08970332decccb0456957ec28fff","repository":{"slug":"p1_test1","id":"18","name":"p1_test1","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"PROJ1","id":"24","name":"project1","public":false,"type":"NORMAL"},"links":{"clone":[{"href":"ssh://git@******/proj1/p1_test1.git","name":"ssh"},{"href":"http://******/scm/proj1/p1_test1.git","name":"http"}],"self":[{"href":"http://******/projects/PROJ1/repos/p1_test1/browse"}]},"public":false}},"toRef":{"id":"refs/heads/master","displayId":"master","latestCommit":"5ef23b0bae0f2f5bf42934eb1919334e0c951f7c","repository":{"slug":"p1_test1","id":"18","name":"p1_test1","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"PROJ1","id":"24","name":"project1","public":false,"type":"NORMAL"},"links":{"clone":[{"href":"ssh://git@******/proj1/p1_test1.git","name":"ssh"},{"href":"http://******/scm/proj1/p1_test1.git","name":"http"}],"self":[{"href":"http://******/projects/PROJ1/repos/p1_test1/browse"}]},"public":false}}},"changes":[]}
Apr 21, 2020 2:16:54 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.processor.BitBucketPPRPullRequestServerPayloadProcessor
Processing BitBucketPPREvent [event=pr, action=opened]
Apr 21, 2020 2:16:54 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver
the selected payload processor is: io.jenkins.plugins.bitbucketpushandpullrequest.processor.BitBucketPPRPullRequestServerPayloadProcessor@14c7d6e8
Apr 21, 2020 2:16:54 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.action.BitBucketPPRPullRequestServerAction
BitBucketPPRPullRequestServerAction was called.
Apr 21, 2020 2:16:54 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering remote [ssh://git@******/proj1/p1_test1.git, http://******/scm/proj1/p1_test1.git]
Apr 21, 2020 2:16:54 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering candidate job debug-BitbucketPushAndPullRequest-pipeline
Apr 21, 2020 2:16:54 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering to poke debug-BitbucketPushAndPullRequest-pipeline
Apr 21, 2020 2:16:54 AM FINE io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRJobProbe
Considering to use trigger Optional[io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRTrigger@492a9b52]
Apr 21, 2020 2:16:54 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
Sending response.
Apr 21, 2020 2:16:54 AM INFO io.jenkins.plugins.bitbucketpushandpullrequest.BitBucketPPRHookReceiver doIndex
Response sent.
```

**Comment by jamyl** [comment]
Hi, 
I had a similar issue.

The first time I add a pipeline job with Bitbucket Server Pull Request, it's working correctly and the SCM changes are detected and it triggers a build.

But after the first build, nothing is detected or matched.
And the reason in my case is because the Server triggers are replaced by "Bitbucket Cloud Pull Request" triggers. 

Is anyone else having the Server triggers replaced by Cloud triggers??  

I tested with plugin to 2.3.3, it's the only one installed related to Bitbucket.
I also tested with an old version 2.0.0 and the same issue. 
Jenkins ver. 2.222.1

Any help is welcome.
Thanks!

**Comment by cdelmonte-zg** [comment]
@heathergithub how is configured the git plugin? 
Is the url the same as ssh://git@******/proj1/p1_test1.git or http://******/scm/proj1/p1_test1.git ?

Do you have also an issue similar to the one described by @jamyl ?

**Comment by jamyl** [comment]
@cdelmonte-zg Even if the checkbox is unchecked, if I create a pipeline job and build it manually the triggers for Cloud are added.

**Comment by heathergithub** [comment]
Hi @cdelmonte-zg, I don't have the similar issue with @jamyl.
The webhook trigger could work now, your guess is correct, the reop url had problem. Sorry for that.

Version informations:
Atlassian Bitbucket server v7.0.1
Jenkins ver. 2.219
plugin 2.3.3

Another 2 questions hope you can help. Many thanks!

**1. How to configure the Jenkins job to only build branch BITBUCKET_SOURCE_BRANCH?**
I set env var BITBUCKET_SOURCE_BRANCH in Jenkins job configuration, but seems that it isn't supported.
And is it possible to build the commit which triggered the PR, not latest comit in BITBUCKET_SOURCE_BRANCH? It's something like a var BITBUCKET_SOURCE_COMMIT_ID

My current setting is
![jenkins-config](https://user-images.githubusercontent.com/16832219/79936081-12432e00-8489-11ea-8831-b3415718591d.png)

Jenkins build output is:
```
Started by user ******: Bitbucket PPR: new pull request created
hudson.plugins.git.GitException: Command "git fetch --tags --progress --prune -- origin +refs/heads/${env.BITBUCKET_SOURCE_BRANCH}:refs/remotes/origin/${env.BITBUCKET_SOURCE_BRANCH}" returned status code 128:
stdout: 
stderr: fatal: Couldn't find remote ref refs/heads/${env.BITBUCKET_SOURCE_BRANCH}

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2044)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:81)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:569)
	at jenkins.plugins.git.GitSCMFileSystem$BuilderImpl.build(GitSCMFileSystem.java:361)
	at jenkins.scm.api.SCMFileSystem.of(SCMFileSystem.java:197)
	at jenkins.scm.api.SCMFileSystem.of(SCMFileSystem.java:173)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:115)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:69)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Finished: FAILURE
```

**2. After Jenkins build finish, no build status is display in Bitbucket page, is this as design?**
My expected build status display is like below picture:
![build_status](https://user-images.githubusercontent.com/16832219/79935037-7fa18f80-8486-11ea-8e98-2615f4c5f390.png)

**Comment by cdelmonte-zg** [comment]
I'm glad to know that it helped :)

Regarding your questions:
1. No, it doesn't work that way. You can use the ENV vars in your goorvy or bash scripts, for example 
If you want to inject variables that way, you need to use the inject env vars, for example parametrizing the job etc.

2. We'll add this funciton in the future.

**Comment by cdelmonte-zg** [comment]
@jamyl Are yu sure, you don't have in your repository a Jenkinsfile? Maybe, that is the reason.

**Comment by heathergithub** [comment]
Thank you for your help @cdelmonte-zg

**Comment by pchodak** [comment]
> Hi,
> I had a similar issue.
> 
> The first time I add a pipeline job with Bitbucket Server Pull Request, it's working correctly and the SCM changes are detected and it triggers a build.
> 
> But after the first build, nothing is detected or matched.
> And the reason in my case is because the Server triggers are replaced by "Bitbucket Cloud Pull Request" triggers.
> 
> Is anyone else having the Server triggers replaced by Cloud triggers??
> 
> I tested with plugin to 2.3.3, it's the only one installed related to Bitbucket.
> I also tested with an old version 2.0.0 and the same issue.
> Jenkins ver. 2.222.1
> 
> Any help is welcome.
> Thanks!

Got the same problem. Did you manage to fix this problem?
